name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: v0-linux-${{ runner.arch }}-${{ hashFiles('Cargo.lock') }}
      - run: mise run check
